// IDataAnalyzer.cs
//  
//  Author:
//       Andreas Reiter <andreas.reiter@student.tugraz.at>
// 
//  Copyright 2011  Andreas Reiter
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
using System;
using System.Xml;
namespace Fuzzer.Analyzers
{
	
	/// <summary>
	/// Analyzes data generated by the fuzzer and writes possible 
	/// vulnerabilities to a specified xml file
	/// </summary>
	public interface IDataAnalyzer
	{
		/// <summary>
		/// Gets or sets the prefix, used for identifying the current data set
		/// </summary>
		string Prefix { get; set; }
		
		/// <summary>
		/// Basepath to read the data from
		/// </summary>
		string Path {get; set;}
		/// <summary>
		/// Setsup the data analyzer
		/// </summary>
		/// <param name="errorlogRoot">
		/// A <see cref="XmlElement"/>
		/// </param>
		void Setup(XmlElement errorlogRoot);
		
		/// <summary>
		/// Starts the analyze process and writes discovered errors and vulnerabilities 
		/// to the specified errorlog
		/// </summary>
		void Analyze(AnalyzeController ctrl);
	}
}

