// DataGeneratorLogger.cs
//  
//  Author:
//       Andreas Reiter <andreas.reiter@student.tugraz.at>
// 
//  Copyright 2011  Andreas Reiter
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
using System;
using System.IO;
using Iaik.Utils;
namespace Fuzzer.DataLoggers
{
	/// <summary>
	/// Logs data generated by any IDataGenerator.
	/// The logs can be replayed using a ReplayDataGenerator
	/// </summary>
	public class DataGeneratorLogger : IDataLogger
	{
		
		private string _path;
		private string _prefix;
		
		private Stream _logStream = null;
		
		public DataGeneratorLogger (string path)
		{
			_path = path;
		}
	

		#region IDataLogger implementation
		public void FinishedFuzzRun ()
		{
			CloseLogStream ();
		}

		public void StartingFuzzRun ()
		{
			CloseLogStream ();
			
			string logFile = BuildLogFile ();
			if (File.Exists (logFile))
				File.Delete (logFile);
			
			_logStream = File.OpenWrite(logFile);
		}

		public string Prefix 
		{
			get { return _prefix; }
			set { _prefix = value;}
		}
		#endregion
		
		public void LogData (byte[] data)
		{
			if (_logStream != null)
				_logStream.Write(data, 0, data.Length);
//				StreamHelper.WriteBytesSafe (data, _logStream);
		}
		
		private void CloseLogStream ()
		{
			if (_logStream != null)
			{
				_logStream.Close ();
				_logStream = null;
			}
		}
		
		/// <summary>
		/// Builds the next stack frame log file
		/// </summary>
		/// <returns></returns>
		private string BuildLogFile ()
		{
			string filename = "";
			
			if (_prefix != null && _prefix != String.Empty)
				filename = _prefix + ".fuzzdata";
			else
				filename = "current.fuzzdata";
			
			return Path.Combine (_path, filename);
			
		}
	}
}

